<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="jade">
  <xacro:property name="width" value=".2" />
  <xacro:property name="leglen" value=".6" />
  <xacro:property name="polelen" value=".2" />
  <xacro:property name="bodylen" value=".6" />
  <xacro:property name="baselen" value=".4" />
  <xacro:property name="wheeldiam" value=".07" />
  <xacro:property name="pi" value="3.1415" />
  
  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0"
	       iyy="1.0" iyz="0.0"
	       izz="1.0" />
    </inertial>
  </xacro:macro>
  
  <!--**********************************************************************-->
  <!-- The main body frame of the robot -->
  <!--**********************************************************************-->
  <link name="base_link">
    <visual>
      <geometry>
	<box size="0.210 0.090 0.0685"/>
      </geometry>
      <material name="gray">
	<color rgba="0.7 0.7 0.7 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
	<box size="0.210 0.090 0.0685"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="0.010"/>
  </link>

  <xacro:macro name="coxa" params="id pos rot">
    <link name="coxa_${id}">
      <origin xyz="0.026 0 0"/>
      <visual>
	<geometry>
	  <box size="0.052 0.048 0.025"/>
	</geometry>
	<material name="gray">
	  <color rgba="0.5 0.5 0.5 1"/>
	</material>
      </visual>
      <xacro:default_inertial mass="0.010"/>
    </link>
    <joint name="coxa_${id}_joint" type="revolute">
      <origin xyz="${pos}" rpy="0 0 ${rot}" />
      <parent link="base_link"/>
      <child link="coxa_${id}"/>
      <limit effort="30" velocity="10" lower="${rot - 1.9}" upper="${rot + 1.9}"/>
    </joint>
  </xacro:macro>

  <xacro:coxa id="1" pos="0.122 0.061 -0.01375" rot="${3.14159/4}" />
  <xacro:coxa id="1R" pos="0.122 -0.061 -0.01375" rot="${-3.14159/4}" />


  <!--**********************************************************************-->
  <!-- Definition of the COXA part -->
  <!--**********************************************************************-->
  <xacro:macro name="wheel" params="number reflect">
    <link name="coxa_${number}">
      <visual>
	<geometry>
	  <cylinder radius="${wheeldiam/2}" length=".1"/>
	</geometry>
	<material name="black">
	  <color rgba="0 0 0 1"/>
	</material>
      </visual>
      <collision>
	<geometry>
	  <cylinder radius="${wheeldiam/2}" length=".1"/>
	</geometry>
      </collision>
      <xacro:default_inertial mass="1"/>
    </link>
  </xacro:macro>
</robot>

