# Odometry
{
    pose:   {
                x : x position
                y : y position
                z : z position
                theta : heading direction
            }
            }
    twist:  {
                vx : velocity in the X direction
                vy : velocity in the Y direction
                vz : velocity in the Z direction
                rx : rotational velocity about the X axis
                ry : rotational velocity about the Y axis
                rz : rotational velocity about the Z axis
            }
}